### ISSUE TITLE
portable version support

### ISSUE THREAD

**Issue by jjw24** [stax76/Flow.Launcher.Plugin.Favorites#1]
Hey how's it going, great plugin. 

Thought I make a couple suggestions if I may.

Current mechanism of saving the conf file to roaming folder wont allow users to use portable mode with this plugin because userdata is kept in the app folder when portable is activated. If there is no difference with using json format instead of conf, you can take advantage of Flow's api using [the load and save settings calls](https://github.com/Flow-Launcher/Flow.Launcher/blob/8942e5567a888068aaf7eabde29aa909387155ca/Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs#L177-L192). This will save it into the right user data location as json format. See usage [here](https://github.com/Flow-Launcher/Flow.Launcher/blob/15db87ccc99aa996244b2472565aaa4e08e72435/Plugins/Flow.Launcher.Plugin.Calculator/Main.cs#L36) and [here](https://github.com/Flow-Launcher/Flow.Launcher/blob/15db87ccc99aa996244b2472565aaa4e08e72435/Plugins/Flow.Launcher.Plugin.Calculator/Settings.cs#L9) as an example.

Also to help users you could also create a settings page in flow's settings' plugin section, so users can add via the UI instead of file.

Hope this helps.

**Comment by stax76** [comment]
> Hey how's it going, great plugin.

Thanks, I work on bringing mpv.net to the MS Store and winget, it makes progress.

> Current mechanism of saving the conf file to roaming folder wont allow users to use portable mode with this plugin because userdata is kept in the app folder when portable is activated.

I should be able to fix it.

> Also to help users you could also create a settings page in flow's settings' plugin section, so users can add via the UI instead of file.

ini/conf is very easy to understand and edit, and I'm an avid VS Code user. Building a decent GUI in contrast isn't easy for me, I'm not very advanced in WPF and MVVM, maybe I build it later, we'll see.

What is probably easy to do is making the refresh automatic (by checking the file modified date).

**Comment by stax76** [comment]
v1.3 supports portable.

And the readme was improved.
