### ISSUE TITLE
Does not work with portable version

### ISSUE THREAD

**Issue by willasm** [stax76/Flow.Launcher.Plugin.Favorites#11]
I have tried putting the conf file in the portable settings folder and %APPDATA%\FlowLauncher\Settings\Favorites.conf
Does not matter where I create it, it never gets loaded.

**Comment by stax76** [comment]
I checked the code, it uses a path relative to the plugin DLL, so it should work.

Portable version support was requested [here](https://github.com/stax76/Flow.Launcher.Plugin.Favorites/issues/1).

**Comment by willasm** [comment]
Was able to get it working. After looking at the code I was able to figure out that the settings file needed to go into "Settings\Favorites.conf". I had it up one level in the "userdata" folder.
