### ISSUE TITLE
Support environment variables in Favorites.conf

### ISSUE THREAD

**Issue by KyleKolander** [stax76/Flow.Launcher.Plugin.Favorites#3]
Could you please add support for environment variable expansion in Favorites.conf?

Any type of notation is fine, but it would be really helpful because I use multiple computers (home and work) and both share a common configuration repository.  The use of environment variables allows for all of this to happen (i.e., same environment variable on each machine, but different values).  FWIW, the USERPROFILE environment variable is the most important.

```
code = "%USERPROFILE%\scoop\apps\vscode\current\Code.exe"
code = "$env:USERPROFILE\scoop\apps\vscode\current\Code.exe"
code = "$USERPROFILE\scoop\apps\vscode\current\Code.exe"
```

**Comment by stax76** [comment]
I can add support for environment variables, using the first variant. Hopefully within a week.

**Comment by stax76** [comment]
The new version is now online.

**Comment by KyleKolander** [comment]
@stax76 - Thanks for doing that!  I tried it out and it works.  This may be due to me not understanding how to update Flow Launcher plugins, but I couldn't get it to update - actually had to uninstall it and then reinstall it to get your latest version.  It would show there was a new version available, but then it would fail to update saying something about already having the same or newer version installed.  It still says version **1.4.0** is installed.  I'm guessing it's because the **plugin.json** file needs to have the version number increased from **1.4.0** to **1.5.0**.

**Comment by stax76** [comment]
Sorry, I missed updating the plugin.json file. I've re-uploaded it now with updated plugin.json file.

**Comment by KyleKolander** [comment]
No worries.  That did the trick!
